### ISSUE TITLE
What does B mean?

### ISSUE THREAD

**Issue by gouchangjiang** [maedoc/popcorn#7]
Merry Chirstmas and happy new year. What does B in [delays.opencl.cl ](https://github.com/maedoc/popcorn/blob/delays/delays.opencl.c#L100C57-L100C57) mean? I have been looking everywhere in the [OpenCL C specification](https://registry.khronos.org/OpenCL/specs/3.0-unified/pdf/OpenCL_C.pdf) but got nothing.

**Comment by gouchangjiang** [comment]
probably, it means the block_size.

**Comment by maedoc** [comment]
hi, it's the batch size, i.e. the number of parallel instances being computed at once.
